# Generated by Django 5.1.5 on 2025-01-28 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='category',
            new_name='news_category',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='category_text',
            new_name='news_text',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='category_title',
            new_name='news_title',
        ),
        migrations.AddField(
            model_name='news',
            name='news_photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_news_count', models.IntegerField()),
                ('user_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.news')),
            ],
        ),
    ]
