# Generated by Django 5.1.5 on 2025-02-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_rename_category_news_news_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
